# GitHub CI build pipeline
name: Awesome Calculator CI build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up python 3.11
      uses: actions/setup-python@v6.0.0
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        cd src
        python -m pip install --upgrade pip
        pip install coverage unittest-xml-reporting
        if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Unit Tests and generate coverage report
      run: |
        cd src
        # python -m unittest -v
        # python tests/testscalculatortests.py 
        python -m xmlrunner tests/testscalculatortests.py  
        coverage run -m unittest
        coverage report
        coverage html
    - name: Archive code coverage html report
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: src/htmlcov
    - name: Run package creation
      run: |
        cd src
        python -m pip install --user --upgrade build
        python -m build
    # - name: Archive package
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: awesome-calculator
    #    path: src/dist    

    - name: Publish Test Results Linux
      uses: EnricoMi/publish-unit-test-result-action/linux@v2
      if: (! cancelled() )
      with: 
          files: |
             src/TEST*.xml
